#!/bin/bash
#
clear
sudo cat > /etc/motd <<EOF
======================================
        type ./SetupVeeamVM.sh
======================================
EOF
echo "Creating a backup of the current profile ..."
# Creates a backup
cp /etc/netplan/00-installer-config.yaml /etc/netplan/00-installer-config.yaml.bk_`date +%Y%m%d%H%M`
rm /etc/netplan/00-installer-config.yaml
# Changes dhcp from 'yes' to 'no'
echo "Disabling DHCP"
sed -i "s/dhcp4: yes/dhcp4: no/g" /etc/netplan/00-installer-config.yaml
# Retrieves the NIC information
echo "Listing current IPs, take note of the interface for the NIC (should be eth0) ..."
ip address
echo
nic=`ip address | awk 'NR==7{print $2}'`
echo "Working with" $nic
# Ask for input on network configuration
read -p "Enter the static IP of the server in CIDR notation: " staticip 
read -p "Enter the IP of your gateway: " gatewayip
read -p "Enter the IP of preferred nameservers (seperated by a coma if more than one): " nameserversip
echo
echo "Ready to apply new IP - NOTE: If you are SSH'd in your connection will drop, hit any key to begin ..."
read -s
cat > /etc/netplan/00-installer-config.yaml <<EOF
network:
  ethernets:
    $nic
      addresses:
      - $staticip
      nameservers:
        addresses: [$nameserversip]
      routes:
      - to: default
        via: $gatewayip
  version: 2
EOF
chown root:root /etc/netplan/00-installer-config.yaml
chmod 700 /etc/netplan/00-installer-config.yaml
sudo netplan apply
echo "Pausing for 10sec then listing interfaces ..."

read -t10
echo "IPSET" > ~/stateipset.txt
rm ~/statenew.txt
ip address
cat /etc/motd
