#!/bin/bash  
vupw="NOT SET"
tapw="NOT SET"
nasip="NOT SET"
lturl="NOT SET"
devnm="/dev/sdb"
installfunction () {
  cat<<EOF
  Starting setup using:
  - veeamuser password: $vupw
  - tabadmin password: $tapw
  - NAS IP: $nasip
  - iSCSI device: $devnm

EOF
echo "Take a checkpoint of the VM now so if something goes wrong you can roll back easily"
echo
read -p -s "Hit any key when ready ..." junk
echo
echo "Enter the tabadmin password when prompted  - updates being done ..."
echo
sudo apt update
sudo apt upgrade -y
sudo apt install -y bmon unzip default-jre
echo
echo "Take note of the iSCSI ID below then hit any key to continue ..."
read -p -s " " junk
sudo cat /etc/iscsi/initiatorname.iscsi
echo
read -s -p "Make sure you configure the NAS now for iSCSI and provide that ID then hit any key to continue... " junk
echo
read -s -p "Hit any key to open the iSCSI config file. Remove the comment before the automatic start and add one before the manual start..." junk
sudo nano /etc/iscsi/iscsid.conf
echo
echo "Restarting iSCSI service ..."
sudo systemctl restart iscsid open-iscsi
echo
echo "Connecting to iSCSI ..."
sudo iscsiadm -m discovery -t sendtargets -p $nasip
echo
echo "Logging in to iSCSI ..."
sudo iscsiadm -m node --login
echo
echo "Creating volume ..."
sudo parted --script $devnm "mklabel gpt"
sudo parted --script $devnm "mkpart primary 0% 100%"
echo 
echo "Formatting volume ..."
sudo mkfs.xfs -b size=4096 -m reflink=1,crc=1 $devnm -f -K
echo
sudo blkid $devnm
read -p -s "Take note of the UUID above then hit any key to conitnue to edit the fstab file ..." junk
echo "Add this line /dev/disk/by-uuid/--the_UUID_FROM ABOVE--/mnt/veeamrepo xfs _netdev 0 0"
read -p -s "Hit any key to continue ..." junk
sudo mkdir /mnt/veeamrepo
sudo nano /etc/fstab
echo
echo "Attempting to mount volume ..."
sudo mount -a
echo "Listing volumes mapped to " $devnm "..."
df -H | greb $devnm
echo
read -p -s "Does this look right? If so hit any key otherwise CTRL+BREAK now and bail ..." junk
echo
echo "Creating veeamuser ..."
sudo useradd veeamuser --create-home -s /bin/bash
yes $vupw | sudo passwd veeamuser
sudo usermod -a -G sudo veeamuser
sudo chown -R veeamuser:veeamuser /mnt/veeamrepo/
sudo chmod 700 /mnt/veeamrepo/
echo
echo "Installing LT agent"
wget -O agent.zip $lturl
unzip agent.zip
cd LTechAgent/
chmod +x install.sh
sudo ./install.sh
read -p -s "Install done, you can verify in the thick client then press any key to continue ..." junk
echo "Script is mostly done - configure Veeam now and when done return to this window"
read -p -s "Hit any key ..." junk
echo "Removing veeamuser from SUDO group"
sudo usermod -a -G sudo veeamuser
exit
}



while :
do
    clear
    cat<<EOF
  VM Setup Script v1.0.0
  =============================
  1) veeamuser password: $vupw
  2) tabadmin password: $tapw
  3) NAS IP: $nasip
  4) iSCSI device: $devnm
  5) LT agent URL: $lturl
  9) Start
  0) Quit 

EOF
    read -n1 -s
    case "$REPLY" in
    "1")  read -p "new veeamuser password : " vupw ;;
    "2")  read -p "new tabadmin password : " tapw ;;
    "3")  read -p "new NAS IP : " nasip ;;
    "4")  read -p "new device id : " devnm ;;
    "5")  read -p "new agent URL : " lturl ;;
    "9")  installfunction ;;
    "0")  exit                      ;;
     * )  echo "invalid option"     ;;
    esac
    sleep 1
done
